**The functions available in the special package are universal functions, which follow broadcasting and 
automatic array looping.**

In [3]:
from scipy import special as sp

In [4]:
#cube root
cub_rot=sp.cbrt([1,8,64])
cub_rot

array([1., 2., 4.])

In [5]:
sp.cbrt([10, 9, 0.1254, 234])

array([2.15443469, 2.08008382, 0.50053277, 6.16224015])

In [6]:
#exponential a^b
from scipy.special import exp10
res = exp10([2, 9])
print(res)

[1.e+02 1.e+09]


In [7]:
1.e+02   #10^2

100.0

In [9]:
#Relative Error Exponential Function
from scipy.special import exprel
res = exprel([-0.25, -0.1, 0, 0.1, 0.25])
print (res)

[0.88479687 0.95162582 1.         1.05170918 1.13610167]


In [10]:
#Log Sum Exponential Function
from scipy.special import logsumexp
import numpy as np
a = np.arange(10)
res = logsumexp(a)
print (res)

9.45862974442671


In [11]:
from scipy.special import lambertw
w = lambertw(1)
print(w)
print( w * np.exp(w))


(0.5671432904097838+0j)
(0.9999999999999999+0j)


In [12]:
#Permutations & Combinations

In [19]:
from scipy.special import comb
res = comb(4, 3, exact = True,repetition=True)
print (res)

20


In [17]:
from scipy.special import perm
res = perm(4, 3, exact = True)
print (res)

24


In [18]:
help(comb)

Help on function comb in module scipy.special.basic:

comb(N, k, exact=False, repetition=False)
    The number of combinations of N things taken k at a time.
    
    This is often expressed as "N choose k".
    
    Parameters
    ----------
    N : int, ndarray
        Number of things.
    k : int, ndarray
        Number of elements taken.
    exact : bool, optional
        If `exact` is False, then floating point precision is used, otherwise
        exact long integer is computed.
    repetition : bool, optional
        If `repetition` is True, then the number of combinations with
        repetition is computed.
    
    Returns
    -------
    val : int, float, ndarray
        The total number of combinations.
    
    See Also
    --------
    binom : Binomial coefficient ufunc
    
    Notes
    -----
    - Array arguments accepted only for exact=False case.
    - If k > N, N < 0, or k < 0, then a 0 is returned.
    
    Examples
    --------
    >>> from scipy.special import co

In [25]:
comb(4,3,repetition =True)

20.0

In [27]:
perm(10,1)

10.0

In [29]:
from scipy.special import gamma
res = gamma([0, 0.5, 1, 5])
print (res)

[        inf  1.77245385  1.         24.        ]
